-- lsp: PHP (intelephense)
--

return {
    cmd = { "intelephense", "--stdio" },
    filetypes = { "php" },
    root_markers = { "composer.json", ".git" },
    settings = {
        intelephense = {
            files = {
                maxSize = 5000000, -- bytes; default 1MB is too small for vendor scanning
                associations = { "*.php", "*.phtml" },
                exclude = {
                    "**/.git/**",
                    "**/node_modules/**",
                    "**/var/cache/**",
                    "**/var/log/**",
                    "**/var/sessions/**",
                    "**/public/build/**",
                    "**/.phpunit.result.cache",
                    "**/var/.phpunit.cache/**",
                    "**/var/.php-cs-fixer.cache",
                },
            },
            environment = {
                phpVersion = "8.5.0",
            },
            stubs = {
                "apache",
                "bcmath",
                "bz2",
                "calendar",
                "com_dotnet",
                "Core",
                "ctype",
                "curl",
                "date",
                "dba",
                "dom",
                "enchant",
                "exif",
                "FFI",
                "fileinfo",
                "filter",
                "fpm",
                "ftp",
                "gd",
                "gettext",
                "gmp",
                "hash",
                "iconv",
                "imap",
                "intl",
                "json",
                "ldap",
                "libxml",
                "mbstring",
                "meta",
                "mysqli",
                "oci8",
                "odbc",
                "openssl",
                "pcntl",
                "pcre",
                "PDO",
                "pdo_ibm",
                "pdo_mysql",
                "pdo_pgsql",
                "pdo_sqlite",
                "pgsql",
                "Phar",
                "posix",
                "pspell",
                "readline",
                "Reflection",
                "session",
                "shmop",
                "SimpleXML",
                "snmp",
                "soap",
                "sockets",
                "sodium",
                "SPL",
                "sqlite3",
                "standard",
                "superglobals",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tidy",
                "tokenizer",
                "xml",
                "xmlreader",
                "xmlrpc",
                "xmlwriter",
                "xsl",
                "Zend OPcache",
                "zip",
                "zlib",
                "wordpress", -- harmless if you don't use it; remove if you want
                "Redis", -- you have ext-redis in composer
                "amqp", -- you have php8.5-amqp in Dockerfile
            },
            completion = {
                insertUseDeclaration = true,
                fullyQualifyGlobalConstantsAndFunctions = false,
                triggerParameterHints = true,
                maxItems = 100,
            },
            format = {
                enable = false, -- we use php-cs-fixer via conform.nvim, not Intelephense's formatter
            },
            diagnostics = {
                enable = true,
                undefinedTypes = true,
                undefinedFunctions = true,
                undefinedConstants = true,
                undefinedClassConstants = true,
                undefinedMethods = true,
                undefinedProperties = true,
                undefinedVariables = true,
                unusedSymbols = true,
                unexpectedTokens = true,
                duplicateSymbols = true,
                argumentCount = true,
                typeErrors = true,
            },
        },
    },
}
